dist: trusty
language: generic
services:
  - docker
notifications:
  email:
    - travis@codelabs.ch
env:
  global:
    - DOCKER_IMG=codelabsch/muen.sk-docker
script:
  - docker pull ${DOCKER_IMG} || true
  - docker build --cache-from ${DOCKER_IMG}
    --build-arg site_branch=${TRAVIS_BRANCH}
    --tag ${DOCKER_IMG}:latest
    .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ${DOCKER_IMG}:latest
