title: SK for x86/64
description: Muen is a separation kernel for the Intel x86/64 microarchitecture
author: Muen Project
asciidoctor:
  :safe: :unsafe
  :base_dir: null
  :attributes:
    allow-uri-read: ''
    compat-mode: '@'
    attribute-missing: 'warn'
    relfileprefix: '../'
    outfilesuffix: '/'
    idprefix: ''
    idseparator: '-'
    icons: 'font'
    sectanchors: ''
    linkattrs: ''
    #source-highlighter: 'highlight.js'
    source-highlighter: 'coderay'
    prewrap: null
minify: true
haml:
  :ugly: true
slim|html:
  :format: :html
# NOTE if no profile is specified, the first with a deploy config is selected
profiles:
  development:
    deploy: null
    #show_drafts: false
  staging:
    deploy: null
  production:
    base_url: https://muen.sk
